WARNING: C:\AnsysDev\GitRepos\PyAnsys\pyfluent-parametric\examples\00-parametric\parametric_static_mixer_1.py failed to execute correctly: Traceback (most recent call last):
  File "C:\AnsysDev\GitRepos\PyAnsys\pyfluent-parametric\examples\00-parametric\parametric_static_mixer_1.py", line 130, in <module>
    study_1 = ParametricStudy(session.solver.root.parametric_studies).initialize()
  File "C:\AnsysDev\GitRepos\PyAnsys\pyfluent-parametric\src\ansys\fluent\parametric\__init__.py", line 181, in initialize
    self._parametric_studies.initialize(
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 638, in __call__
    return self.flproxy.execute_cmd(self._parent.path, self.obj_name, **newkwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\services\settings.py", line 86, in _fn
    return fn(self, *args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\services\settings.py", line 273, in execute_cmd
    response = self.__service_impl.execute_cmd(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: Required Ensight packages are not detected. Ensure Ensight has been installed before creating simulation reports
Error Object: #f


Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
C:\AnsysDev\GitRepos\PyAnsys\pyfluent-parametric\examples\00-parametric\parametric_static_mixer_1.py failed leaving traceback:
Traceback (most recent call last):
  File "C:\AnsysDev\GitRepos\PyAnsys\pyfluent-parametric\examples\00-parametric\parametric_static_mixer_1.py", line 130, in <module>
    study_1 = ParametricStudy(session.solver.root.parametric_studies).initialize()
  File "C:\AnsysDev\GitRepos\PyAnsys\pyfluent-parametric\src\ansys\fluent\parametric\__init__.py", line 181, in initialize
    self._parametric_studies.initialize(
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 638, in __call__
    return self.flproxy.execute_cmd(self._parent.path, self.obj_name, **newkwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\services\settings.py", line 86, in _fn
    return fn(self, *args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\services\settings.py", line 273, in execute_cmd
    response = self.__service_impl.execute_cmd(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: Required Ensight packages are not detected. Ensure Ensight has been installed before creating simulation reports
Error Object: #f


-------------------------------------------------------------------------------
